apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-bitnami
  namespace: argocd # replace with your Argo CD namespace if different
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.38
    helm:
      values: |
        auth:
          postgresPassword: mysecurepassword
          username: myuser
          password: myuserpassword
          database: mydatabase
        primary:
          persistence:
            enabled: true
            size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true