apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  project: default
  source:
    chart:
      chart: redis
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 20.13.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
